/**
 * Caches Ollama-generated capability analysis per contractor.
 *
 * Generated by /api/intelligence/contractor-analysis. Re-renders the
 * Strengths/Weaknesses/Partnership-angle section on contractor/partner/
 * competitor detail pages without re-burning Ollama cycles. 30-day TTL
 * before regeneration so the data stays roughly current as past-awards
 * accumulate.
 */

alter table public.contractors
    add column if not exists capability_summary_ai jsonb,
    add column if not exists capability_summary_refreshed_at timestamptz,
    add column if not exists capability_summary_source text;

-- Index for the "regenerate stale" cron we'll add later — finds contractors
-- whose AI summary is missing or older than 30 days.
create index if not exists idx_contractors_capability_stale
    on public.contractors(capability_summary_refreshed_at nulls first)
    where uei is not null;

-- Index for sorting Contract Winners by award volume (existing column from
-- migration 040 lineage). Speeds up the new /api/contractors/list endpoint.
create index if not exists idx_contractors_award_volume
    on public.contractors(total_award_volume desc nulls last)
    where total_award_volume is not null;

create index if not exists idx_contractors_award_count
    on public.contractors(federal_awards_count desc nulls last)
    where federal_awards_count is not null and federal_awards_count > 0;
