-- 127: SUPERSEDED by migration 130. DO NOT APPLY THIS FILE.
--
-- This migration was authored 2026-06-08 by the cron-followup workflow agent
-- to bump analyze_attachments queue priority from 4 → 8. Unfortunately it
-- predated the source-tuned routing fanout (migrations 121-124) and was
-- written against the old trigger shape. Applying it AFTER 121-124 would
-- have reverted the city/county/state/federal routing back to the generic
-- extract_structured_reqs task type — silently killing the source-tuned
-- extraction work.
--
-- The correct combined change is in migration
-- 130_bump_analyze_attachments_priority_preserve_routing.sql, which keeps
-- 124's routing intact AND bumps the analyze_attachments priority + back-
-- fills the 12k+ already-pending rows.
--
-- This file is kept (instead of deleted) so the migration history stays
-- continuous. Body is intentionally empty — supabase tracks it as applied
-- but it makes no schema changes.

-- (no-op)
select 1;
