import { NextRequest, NextResponse } from "next/server";
import { fetchRefDomains } from "@/lib/backlinks/semrush";
import { classify } from "@/lib/backlinks/classify";
import { adminSupabase, recordAgentRun, authorizeCron } from "@/lib/backlinks/admin-client";

export const maxDuration = 300;

const OUR_DOMAIN = "capturepilot.com";

/**
 * Pulls our own refdomains from Semrush, classifies, and writes a
 * disavow.txt file content into the backlink_agents.last_run_summary so
 * the admin UI can offer "Download disavow.txt".
 *
 * (We don't write to public/disavow.txt at request-time because Vercel's
 * filesystem is read-only — the file is served via an admin endpoint.)
 */
export async function GET(req: NextRequest) {
  if (!authorizeCron(req.headers.get("authorization"))) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const started = Date.now();

  const summary = {
    refdomains_seen: 0,
    spam_count: 0,
    disavow_lines: [] as string[],
    error: null as string | null,
  };

  try {
    const rows = await fetchRefDomains(OUR_DOMAIN, 500);
    summary.refdomains_seen = rows.length;
    const spamDomains = rows
      .map(r => ({ row: r, cls: classify(r) }))
      .filter(x => x.cls.isSpam)
      .map(x => x.row.domain);
    summary.spam_count = spamDomains.length;
    summary.disavow_lines = [
      "# CapturePilot disavow file — auto-generated by backlink_disavow cron",
      `# Generated: ${new Date().toISOString()}`,
      `# Source: Semrush refdomains for ${OUR_DOMAIN}`,
      "",
      ...spamDomains.map(d => `domain:${d}`),
    ];
  } catch (err) {
    summary.error = (err as Error).message;
  }

  await recordAgentRun(
    "disavow_generator",
    summary.error ? "failure" : "success",
    summary,
    Date.now() - started,
  );
  return NextResponse.json({ ok: true, summary });
}
