export interface NaicsCode {
    code: string;
    label: string;
    popular?: boolean;
}

export const NAICS_CODES: NaicsCode[] = [
    // Popular / Most common in gov contracting (shown first)
    { code: "561720", label: "Janitorial Services", popular: true },
    { code: "561210", label: "Facilities Support Services", popular: true },
    { code: "561730", label: "Landscaping Services", popular: true },
    { code: "561710", label: "Exterminating & Pest Control", popular: true },
    { code: "236220", label: "Commercial Building Construction", popular: true },
    { code: "238210", label: "Electrical Contractors", popular: true },
    { code: "238220", label: "Plumbing & HVAC Contractors", popular: true },
    { code: "238320", label: "Painting & Wall Covering", popular: true },
    { code: "238910", label: "Site Preparation Contractors", popular: true },
    { code: "541330", label: "Engineering Services", popular: true },
    { code: "541512", label: "Computer Systems Design", popular: true },
    { code: "541611", label: "Admin Management Consulting", popular: true },
    { code: "541690", label: "Other Scientific/Technical Consulting", popular: true },
    { code: "561320", label: "Temporary Staffing Services", popular: true },
    { code: "561612", label: "Security Guards & Patrol Services", popular: true },
    { code: "562111", label: "Solid Waste Collection", popular: true },
    { code: "562910", label: "Remediation Services", popular: true },
    { code: "488190", label: "Other Support Activities for Air Transportation", popular: true },
    { code: "484110", label: "General Freight Trucking, Local", popular: true },
    { code: "484121", label: "General Freight Trucking, Long-Distance (Truckload)", popular: true },
    { code: "484122", label: "General Freight Trucking, Long-Distance (LTL)", popular: true },
    { code: "493110", label: "General Warehousing and Storage", popular: true },
    { code: "492110", label: "Couriers and Express Delivery Services", popular: true },
    { code: "811310", label: "Commercial Machinery Repair & Maintenance", popular: true },

    // Additional common government contracting NAICS codes
    { code: "236210", label: "Industrial Building Construction" },
    { code: "237110", label: "Water & Sewer Line Construction" },
    { code: "237310", label: "Highway, Street & Bridge Construction" },
    { code: "237990", label: "Other Heavy & Civil Engineering" },
    { code: "238110", label: "Poured Concrete Foundation & Structure" },
    { code: "238120", label: "Structural Steel & Precast Concrete" },
    { code: "238130", label: "Framing Contractors" },
    { code: "238140", label: "Masonry Contractors" },
    { code: "238150", label: "Glass & Glazing Contractors" },
    { code: "238160", label: "Roofing Contractors" },
    { code: "238170", label: "Siding Contractors" },
    { code: "238190", label: "Other Foundation & Exterior Contractors" },
    { code: "238290", label: "Other Building Equipment Contractors" },
    { code: "238310", label: "Drywall & Insulation Contractors" },
    { code: "238330", label: "Flooring Contractors" },
    { code: "238340", label: "Tile & Terrazzo Contractors" },
    { code: "238350", label: "Finish Carpentry Contractors" },
    { code: "238390", label: "Other Building Finishing Contractors" },
    { code: "238990", label: "All Other Specialty Trade Contractors" },
    { code: "332710", label: "Machine Shops" },
    { code: "332999", label: "All Other Miscellaneous Fabricated Metal" },
    { code: "334111", label: "Electronic Computer Manufacturing" },
    { code: "334511", label: "Search, Detection & Navigation Instruments" },
    { code: "336411", label: "Aircraft Manufacturing" },
    { code: "336413", label: "Other Aircraft Parts Manufacturing" },
    { code: "336414", label: "Guided Missile & Space Vehicle Manufacturing" },
    { code: "336611", label: "Ship Building & Repairing" },
    { code: "336992", label: "Military Armored Vehicle Manufacturing" },
    { code: "423430", label: "Computer Equipment Merchant Wholesalers" },
    { code: "423860", label: "Transportation Equipment Wholesale" },
    { code: "424120", label: "Stationery & Office Supplies" },
    { code: "425120", label: "Wholesale Trade Agents & Brokers" },
    { code: "484210", label: "Used Household and Office Goods Moving" },
    { code: "484220", label: "Specialized Freight Trucking, Local" },
    { code: "484230", label: "Specialized Freight Trucking, Long-Distance" },
    { code: "488110", label: "Air Traffic Control" },
    { code: "488119", label: "Other Airport Operations" },
    { code: "488210", label: "Support Activities for Rail Transportation" },
    { code: "488310", label: "Port and Harbor Operations" },
    { code: "488320", label: "Marine Cargo Handling" },
    { code: "488330", label: "Navigational Services to Shipping" },
    { code: "488390", label: "Other Support Activities for Water Transportation" },
    { code: "488410", label: "Motor Vehicle Towing" },
    { code: "488490", label: "Other Support Activities for Road Transportation" },
    { code: "488510", label: "Freight Transportation Arrangement" },
    { code: "488991", label: "Packing and Crating" },
    { code: "488999", label: "All Other Support Activities for Transportation" },
    { code: "492210", label: "Local Messengers and Local Delivery" },
    { code: "493120", label: "Refrigerated Warehousing and Storage" },
    { code: "493130", label: "Farm Product Warehousing and Storage" },
    { code: "493190", label: "Other Warehousing and Storage" },
    { code: "511210", label: "Software Publishers" },
    { code: "517110", label: "Wired Telecommunications Carriers" },
    { code: "517210", label: "Wireless Telecommunications" },
    { code: "518210", label: "Data Processing & Hosting Services" },
    { code: "519130", label: "Internet Publishing & Web Search Portals" },
    { code: "541310", label: "Architectural Services" },
    { code: "541320", label: "Landscape Architectural Services" },
    { code: "541340", label: "Drafting Services" },
    { code: "541350", label: "Building Inspection Services" },
    { code: "541370", label: "Surveying & Mapping Services" },
    { code: "541380", label: "Testing Laboratories" },
    { code: "541410", label: "Interior Design Services" },
    { code: "541430", label: "Graphic Design Services" },
    { code: "541490", label: "Other Specialized Design Services" },
    { code: "541511", label: "Custom Computer Programming" },
    { code: "541513", label: "Computer Facilities Management" },
    { code: "541519", label: "Other Computer Related Services" },
    { code: "541612", label: "Human Resources Consulting" },
    { code: "541613", label: "Marketing Consulting" },
    { code: "541614", label: "Process & Logistics Consulting" },
    { code: "541618", label: "Other Management Consulting" },
    { code: "541620", label: "Environmental Consulting" },
    { code: "541711", label: "R&D in Biotechnology" },
    { code: "541712", label: "R&D in Physical & Engineering Sciences" },
    { code: "541715", label: "R&D in Social Sciences & Humanities" },
    { code: "541720", label: "Research & Development (Other)" },
    { code: "541810", label: "Advertising Agencies" },
    { code: "541820", label: "Public Relations Agencies" },
    { code: "541910", label: "Marketing Research & Public Opinion" },
    { code: "541922", label: "Commercial Photography" },
    { code: "541930", label: "Translation & Interpretation" },
    { code: "541990", label: "All Other Professional & Technical" },
    { code: "561110", label: "Office Administrative Services" },
    { code: "561311", label: "Employment Placement Agencies" },
    { code: "561410", label: "Document Preparation Services" },
    { code: "561421", label: "Telephone Answering Services" },
    { code: "561439", label: "Other Business Service Centers" },
    { code: "561440", label: "Collection Agencies" },
    { code: "561450", label: "Credit Bureaus" },
    { code: "561491", label: "Repossession Services" },
    { code: "561499", label: "All Other Business Support Services" },
    { code: "561510", label: "Travel Agencies" },
    { code: "561520", label: "Tour Operators" },
    { code: "561611", label: "Investigation Services" },
    { code: "561613", label: "Armored Car Services" },
    { code: "561621", label: "Security Systems Services (except Locksmiths)" },
    { code: "561740", label: "Carpet & Upholstery Cleaning" },
    { code: "561790", label: "Other Services to Buildings" },
    { code: "561910", label: "Packaging & Labeling Services" },
    { code: "561990", label: "All Other Support Services" },
    { code: "562112", label: "Hazardous Waste Collection" },
    { code: "562119", label: "Other Waste Collection" },
    { code: "562211", label: "Hazardous Waste Treatment & Disposal" },
    { code: "562219", label: "Other Nonhazardous Waste Treatment" },
    { code: "562998", label: "All Other Miscellaneous Waste Management" },
    { code: "611430", label: "Professional & Management Development Training" },
    { code: "611519", label: "Other Technical & Trade Schools" },
    { code: "611710", label: "Educational Support Services" },
    { code: "621999", label: "All Other Miscellaneous Health Services" },
    { code: "722310", label: "Food Service Contractors" },
    { code: "811111", label: "General Automotive Repair" },
    { code: "811210", label: "Electronic Equipment Repair" },
    { code: "811219", label: "Other Electronic Equipment Repair" },
    { code: "811411", label: "Home & Garden Equipment Repair" },
    { code: "811412", label: "Appliance Repair & Maintenance" },
    { code: "812332", label: "Industrial Launderers" },
    { code: "928110", label: "National Security" },
];

export function searchNaics(query: string): NaicsCode[] {
    if (!query.trim()) return NAICS_CODES.filter((n) => n.popular);

    const q = query.toLowerCase().trim();
    return NAICS_CODES.filter(
        (n) =>
            n.code.includes(q) ||
            n.label.toLowerCase().includes(q)
    );
}
