#!/usr/bin/env node
/**
 * Generate a Mermaid ER diagram of the production schema by querying
 * information_schema directly (no local pg_dump needed). Writes to
 * docs/DB_SCHEMA.md so it can be checked in.
 *
 * Usage:
 *   SUPABASE_URL=... SUPABASE_SERVICE_KEY=... node tools/31_db_schema_diagram.mjs
 *
 * Output is a single Markdown file with one mermaid erDiagram block.
 * Excludes auth.*, storage.*, realtime.* — those are Supabase internals
 * we don't author.
 */

import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_KEY.");
    process.exit(1);
}

const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, { auth: { persistSession: false } });

// Pull all user-schema tables, their columns, and primary/foreign keys.
// We use a single RPC-able view if available, else split into three queries.
async function fetchSchema() {
    const tablesQ = await sb.rpc("exec_sql_readonly", {
        sql: `select table_name from information_schema.tables
              where table_schema = 'public' and table_type = 'BASE TABLE'
              order by table_name`,
    }).catch(() => ({ data: null }));

    // Fallback when exec_sql_readonly isn't available: hit the REST schema
    // discovery endpoint via direct HTTP. Most Supabase projects don't have
    // exec_sql_readonly enabled so this is the realistic path.
    if (!tablesQ.data) {
        const res = await fetch(`${SUPABASE_URL}/rest/v1/?apikey=${SUPABASE_SERVICE_KEY}`, {
            headers: { Accept: "application/openapi+json" },
        });
        if (!res.ok) throw new Error(`Schema fetch failed: ${res.status}`);
        const openapi = await res.json();
        return openapiToSchema(openapi);
    }
    return null;
}

function openapiToSchema(openapi) {
    const tables = [];
    const defs = openapi.definitions || {};
    for (const [name, def] of Object.entries(defs)) {
        const cols = [];
        const props = def.properties || {};
        for (const [colName, colDef] of Object.entries(props)) {
            const isPk = (def.description || "").includes(`<${colName}> primary key`)
                || (colDef.description || "").includes("Primary Key");
            const isFk = (colDef.description || "").match(/`.*\.(\w+)`<fk table='([\w_]+)'/);
            cols.push({
                name: colName,
                type: colDef.format || colDef.type || "text",
                pk: isPk,
                fk: isFk ? isFk[2] : null,
            });
        }
        tables.push({ name, columns: cols });
    }
    return tables;
}

function generateMermaid(tables) {
    const lines = ["```mermaid", "erDiagram"];
    // Table → columns
    for (const t of tables) {
        if (t.columns.length === 0) continue;
        lines.push(`    ${t.name} {`);
        for (const c of t.columns.slice(0, 15)) {
            // Mermaid expects "type name" pairs. Trim noise types to keep
            // diagram readable.
            const safeType = c.type.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 20);
            const safeName = c.name.replace(/[^a-zA-Z0-9_]/g, "_");
            const marker = c.pk ? "PK" : c.fk ? "FK" : "";
            lines.push(`        ${safeType} ${safeName} ${marker}`.trimEnd());
        }
        if (t.columns.length > 15) lines.push(`        text more_columns "${t.columns.length - 15} additional cols"`);
        lines.push("    }");
    }
    // Foreign-key edges
    for (const t of tables) {
        for (const c of t.columns) {
            if (c.fk && tables.find(tt => tt.name === c.fk)) {
                lines.push(`    ${c.fk} ||--o{ ${t.name} : "${c.name}"`);
            }
        }
    }
    lines.push("```");
    return lines.join("\n");
}

(async () => {
    console.log("Fetching schema…");
    const tables = await fetchSchema();
    if (!tables || tables.length === 0) {
        console.error("No tables found. Verify SUPABASE_SERVICE_KEY has rights and the project is exposing REST.");
        process.exit(2);
    }
    console.log(`Got ${tables.length} tables.`);
    const mermaid = generateMermaid(tables);
    const md = [
        "# Database Schema",
        "",
        "_Auto-generated by `tools/31_db_schema_diagram.mjs`. Do not edit by hand —_",
        "_re-run after schema changes (typically post-migration)._",
        "",
        `Generated: ${new Date().toISOString()}`,
        `Tables: ${tables.length}`,
        "",
        "## Entity-Relationship Diagram",
        "",
        mermaid,
        "",
        "## Table list",
        "",
        ...tables.map(t => `- \`${t.name}\` — ${t.columns.length} columns`),
        "",
    ].join("\n");
    writeFileSync("docs/DB_SCHEMA.md", md);
    console.log("Wrote docs/DB_SCHEMA.md");
})();
